services:
  # --- INGRESS ---
  traefik:
    image: "traefik:v3.0"
    container_name: "psb_traefik"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:${TRAEFIK_INGRESS_WEB_PORT}"
      - "--entrypoints.dashboard.address=:${TRAEFIK_DASHBOARD_PORT}"
      - "--log.level=INFO"
    ports:
      - "${TRAEFIK_INGRESS_WEB_PORT}:${TRAEFIK_INGRESS_WEB_PORT}"
      - "${TRAEFIK_DASHBOARD_PORT}:${TRAEFIK_DASHBOARD_PORT}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - psb-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=dashboard"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=user:${TRAEFIK_PWDD}"
    restart: unless-stopped

  # --- APPLICATION SERVICES ---
  frontend:
    build:
      context: ../src/frontend
      dockerfile: Dockerfile
    container_name: psb_frontend
    networks:
      - psb-net
    volumes:
      - ./conf/frontend_conf.js:/usr/share/nginx/html/config.js:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_FQDN}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    restart: unless-stopped

  backend:
    build:
      context: ../src/backend
      dockerfile: Dockerfile
    container_name: psb_backend
    networks:
      - psb-net
    depends_on:
      - clickhouse
      - coordinator
    environment:
      - CORS_ALLOWED_ORIGINS=${BACKEND_CORS_ORIGIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_FQDN}`) && ( PathPrefix(`/api`) || Path(`/healthy`))"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.backend.middlewares=api-ratelimit"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.average=40"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.burst=60"
    restart: unless-stopped

  # --- CLICKHOUSE ---
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: psb_clickhouse
    # Prod - remove port access
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # native tcp
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/ch_logs:/var/log/clickhouse-server
      # persistance
      - ./clickhouse/ch_data:/var/lib/clickhouse
      # for the dataset loading
      - ./clickhouse/Dataset_case_1:/var/lib/clickhouse/user_files/dataset:ro
      # manage authz
      - ./clickhouse/ch_auth:/etc/clickhouse-server/users.d:ro
      - ./clickhouse/ch_config:/etc/clickhouse-server/config.d:ro
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    networks:
      - psb-net
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- ORCHESTRATION ---
  coordinator:
    build:
      context: ../src/coordinator
      dockerfile: Dockerfile
    container_name: psb_coordinator
    environment:
      - CH_HOST=clickhouse
      - CH_PORT=8123
      - BATCH_SIZE=5000
    networks:
      - psb-net
    depends_on:
      clickhouse:
        condition: service_healthy
    restart: always

  # --- OFFER WORKERS ---
  worker:
    build:
      context: ../src/offerworker
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: "1.0"
          memory: 2G # FAISS requires memory.............
    environment:
      - COORDINATOR_URL=http://coordinator:8000
      - CH_HOST=clickhouse
      - CH_PORT=8123
    volumes:
      # mount index
      - ./services/worker/index.faiss:/app/index.faiss:ro
    networks:
      - psb-net
    depends_on:
      coordinator:
        condition: service_started
      clickhouse:
        condition: service_healthy
    restart: on-failure

# --- NETWORKING ---
networks:
  psb-net:
    driver: bridge
